### PR TITLE
fix(bot/auto-thread): Set first filename as thread title when message content is empty

### LINKED ISSUE #277: [bot]: fix thread naming when only image is sent
### aspect

Event Listener

### Suggestion?

When just an image is sent with no message content, the bot should make a thread with name "author - image", or a similarly suitable file name (name TBC)

### Possible Solutions

We need to add another condition in the auto thread event listener when no message content is sent

### Extra Information

N/A

### PR DESCRIPTION
**Pull request by JoltCode**
# Description

- Adds support for using attachments on the auto thread feature

Fixes #277 (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- A test has been added to the auto-thread testing file

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have updated .env.example if I added a new environment variable
- [x] My PR title follows the [semantic commits](https://www.conventionalcommits.org/en/v1.0.0/) style

### CODE REVIEW

File: apps/discord-bot/src/listeners/events/auto-thread.ts [hunk 1]
```diff
@@ -17,11 +17,15 @@ async function autoThread(channelSettings: ChannelWithFlags, message: Message) {
 	if (!isHumanMessage(message)) return;
 	if (message.type !== MessageType.Default) return;
 	if (message.thread) return;
-	// Channel is text based, and message has been sent by a human
+	const authorName = message.member?.nickname ?? message.author.username;
+
+	let textTitle = `${authorName} - ${message.cleanContent}`;
+	if (message.attachments.size > 0 && message.content.length === 0) {
+		textTitle = `${authorName} - ${
```
Comment (RhysSullivan) [inline apps/discord-bot/src/listeners/events/auto-thread.ts:24]: Instead of setting the text title again, set a variable like "thread title" make it equal to clean content and then use the attachment name if it's available

**Review by RhysSullivan — CHANGES_REQUESTED** [review]

File: apps/discord-bot/src/listeners/events/auto-thread.ts (hunk 1 above)
Comment (JoltCode) [reply apps/discord-bot/src/listeners/events/auto-thread.ts]: Fixed :+1:

**Review by RhysSullivan — APPROVED** [review]
